[AR-1614] Shell for rendering widget website
availproject/auth pull request #3
Opened 2022-02-23 04:08 UTC by karthik-durai

1. Render button - on clicking of that widget iframe container opens.
2. Widget iframe container displays the widget site.

2022-02-23 11:35 UTC, shrinathprabhu commented on src/wallet-widget/style.css
> +  --widget-container-height-mobile: 375px;
Can we use rem instead of px?

2022-02-24 08:02 UTC, karthik-durai commented on src/wallet-widget/style.css
> +  --widget-container-height-mobile: 375px;
this will be part of the app, so setting relative units may create inconsistencies. @shrinathprabhu

2022-02-24 09:14 UTC, ajithranka requested changes

2022-02-24 09:14 UTC, ajithranka commented on src/wallet-widget/example/index.html
> +    <meta charset="UTF-8">
[style] Indent with two spaces and add an empty line at the end of the file. There's missing trailing commas (line 18) and semicolons (line 19). Do you have auto-formatting setup with Prettier?

2022-02-24 09:14 UTC, ajithranka commented on src/wallet-widget/example/index.html
> +            theme: 'light'
A structure like the one below does not expose the structure of the shell (button, header) and can be extended more easily if we add more themes or orientations.

```suggestion
            assets: {
              logos: {
                vertical: {
                  light: './assets/images/logo_vertical_light.png',
                  dark: './assets/images/logo_vertical_dark.png',
                },
                horizontal: {
                  light: './assets/images/logo_horizontal_light.png',
                  dark: './assets/images/logo_horizontal_dark.png',
                },
             },
            theme: 'light',
```

2022-02-24 09:14 UTC, ajithranka commented on src/wallet-widget/style.css
> +  right: 3%;
Let's use fixed values here instead relative percentages (30px for desktop, 10px for mobile). The difference in values gets prominent on wide screen displays.

| relative (`width: 3%; height: 3%`) | absolute (width: `30px; height: 30px`) |
|--------|----------|
| ![relative](https://user-images.githubusercontent.com/11095038/155492177-9dc99ac5-278f-4751-a616-2fef1ac63832.png) | ![absolute](https://user-images.githubusercontent.com/11095038/155492200-6e759aaa-5ed4-4bca-83cc-0b4fa42fb34b.png) |

2022-02-24 09:14 UTC, ajithranka commented on src/wallet-widget/widget.js
> +function initWidgetUI(config = {}) {
We can't have a default value here and should throw an error if the config object is missing.

2022-02-25 06:02 UTC, shrinathprabhu approved these changes

2022-03-01 06:02 UTC, closed without merging