[AR-1614] build widget shell
availproject/auth pull request #6
Opened 2022-03-01 11:45 UTC by karthik-durai

- Created Widget bubble
- Created Widget IFrame
- Added styles based on provided design
- Created and connected handlers to open and close widget iframe

2022-03-01 12:20 UTC, ajithranka requested changes

2022-03-01 12:20 UTC, ajithranka commented on examples/index.js
> +  assets: {
See this [comment](https://github.com/arcana-network/wallet/pull/3/files#r813647837). We should organise it as a nested object to make it easier to extend with more orientations or themes.

```
assets:
  logo:
    horizontal:
      dark:
      light:
    vertical:
      dark:
      light:
```

2022-03-01 12:20 UTC, ajithranka commented on src/interfaces.ts
> +}
- Name as `IThemeConfig` to match the naming convention for other interfaces.
- Use the nesting structure from the above comment.
- Create a new `type Theme = "light" | "dark"` and use it as `theme: Theme`.

2022-03-01 12:20 UTC, ajithranka commented on src/utils.ts
> +}
- Pass `themeConfig: IThemeConfig` as a parameter.
- Check spacing between `if` and conditions.
- Check `theme = "light"`.

2022-03-01 12:20 UTC, ajithranka commented on src/utils.ts
> +export { getWalletType, getWidgetButtonImage }
Add an empty line at the end of files.

2022-03-01 12:20 UTC, ajithranka commented on src/utils.ts
> +}
Refactor to `getLogo(themeConfig: IThemeConfig, orientation: Orientation)` to make this more general.

2022-03-01 12:20 UTC, ajithranka commented on src/iframeWrapper.ts
>          });
Let's bring our `element` helper here to clean up the DOM creation.

2022-03-04 06:17 UTC, ajithranka approved these changes
This looks great, @karthik-durai! 😄

2022-03-04 06:17 UTC, ajithranka commented on src/utils.ts
> +const createDomElement = (type: string, props: object, ...children: any) => {
I think we can refine the types further here. Do you mind checking if this works?

```suggestion
const createDomElement = (type: string, props: object, ...children: HTMLElement[]): HTMLElement => {
```

2022-03-04 06:18 UTC, ajithranka commented
@makylfang Adding you to the reviewers list as well. Please do let us know if you spot any issues.

2022-03-04 07:09 UTC, shrinathprabhu approved these changes

2022-03-04 07:21 UTC, makylfang approved these changes

2022-03-04 08:01 UTC, karthik-durai commented on src/utils.ts
> +const createDomElement = (type: string, props: object, ...children: any) => {
@ajithranka made the suggested changes, let me know your feedback. [commit-link](https://github.com/arcana-network/wallet/pull/6/commits/f092eb90c18113394d1e3d58641ee967b4f4685a)

2022-03-04 08:51 UTC, merged