[AR-1765] Implement responsiveness for wallet shell
availproject/auth pull request #7
Opened 2022-03-04 11:28 UTC by karthik-durai

1. Defined Viewport sizes.
2. Used View port sizes to render widget shell for different screen sizes.

<img width="339" alt="Screenshot 2022-03-04 at 4 55 27 PM" src="https://user-images.githubusercontent.com/40512676/156755382-a9f73be1-383f-4aa5-8fb5-55c509e0bd69.png">

<img width="339" alt="Screenshot 2022-03-04 at 4 55 32 PM" src="https://user-images.githubusercontent.com/40512676/156755235-e1774a7c-c1fb-4597-a5ac-ad1f5acdc9cd.png">

<img width="867" alt="Screenshot 2022-03-04 at 4 55 47 PM" src="https://user-images.githubusercontent.com/40512676/156755245-155c04f2-28ed-4184-8e69-4d0d76163779.png">

<img width="867" alt="Screenshot 2022-03-04 at 4 55 52 PM" src="https://user-images.githubusercontent.com/40512676/156755255-f1323d94-ed0e-4fb8-9dc4-6ce51d42c6ad.png">

2022-03-07 05:42 UTC, ajithranka requested changes

2022-03-07 05:42 UTC, ajithranka commented on src/styles.ts
> +  right: VIEWPORT_SMALL ? "20px" : "30px",
In this implementation, we doesn't resize the wallet dimensions when the viewport width changes. We can attach a listener to the window resize event to get around this:

```js
const BREAKPOINT_SMALL = 768

function resizeWalletShell() {
  const isViewportSmall = window.matchMedia(`(max-width: ${BREAKPOINT_SMALL}px)`).matches
  const $bubble = document.querySelector('.arcana-widget-bubble')
  const $frame = document.querySelector('.arcana-widget-frame')
  if (isViewportSmall) {
    $bubble.style.right = "20px"
    $bubble.style.bottom = "20px"
    $frame.style.width = "375px"
    $frame.style.height = "235px"
    ...
  } else {
    ...
  }
}

 // Set dimensions on init:
resizeWalletShell()

// Call resizeWalletShell when window resizes:
document.getEventListener("resize", resizeWalletShell)

// If we are explicitly destroying the UI, then we should
// also remove the event listener:
function destoryUI() {
  ...
  document.removeEventListener("resize", resizeWalletShell)
}
```

2022-03-08 03:57 UTC, ajithranka approved these changes
Looks good!

2022-03-08 04:21 UTC, karthik-durai commented on src/styles.ts
> +  right: VIEWPORT_SMALL ? "20px" : "30px",
suggested changes done.

2022-03-08 04:47 UTC, shrinathprabhu approved these changes

2022-03-08 05:20 UTC, merged