Add eslint and prettier
availproject/auth pull request #8
Opened 2022-03-07 06:07 UTC by makylfang

2022-03-07 08:34 UTC, karthik-durai commented on .prettierrc
> +    "semi": true,
shall we set `semi` to `false`? it makes code bit cleaner.

2022-03-07 08:35 UTC, makylfang commented on .prettierrc
> +    "semi": true,
ok sure

2022-03-07 09:16 UTC, ajithranka requested changes

2022-03-07 09:16 UTC, ajithranka commented on .eslintrc.json
> +        "eslint:recommended",
Instead of relying on editor plugins for linting, we should install eslint and related packages as dev dependencies. 

```
yarn add --dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
```

We'll also need to include `eslint-config-prettier` for handling conflicts between prettier and eslint,

```
yarn add --dev eslint-config-prettier
```

and include it in extends,

```
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
```
 
We can add a lint script to the package.json:

```
"lint": "eslint --ext .ts src"
```

Running this script lists 37 errors (mostly `any` type annotations) that will need to be fixed.

2022-03-07 09:16 UTC, ajithranka commented on .prettierrc
> +    "arrowParens": "always",
Same as with eslint, we should add prettier as a dev dependency,

```
yarn add --dev prettier
```

and include a script in package.json for formatting:

```
"format": "prettier --ignore-path .gitignore --write ."
```

Running this script should reformat all files in the project including these config files.

2022-03-07 09:16 UTC, ajithranka commented on .prettierrc
> +    "tabWidth": 2,
Most of these options are default in Prettier. We can create a much small config file including only the differences:

```
{
  "semi": false,
  "singleQuote": true
}
```

2022-03-07 09:17 UTC, karthik-durai commented on .eslintrc.json
> +        "eslint:recommended",
also we can use `husky` and `lint-staged`. @ajithranka

2022-04-11 14:05 UTC, makylfang commented
This commit [778bd14](https://github.com/arcana-network/wallet/pull/8/commits/778bd1462c6c330248ecd8b7d9ebade0d21bac51) has the changes suggested, I forgot to update the commit message. 

- Added eslint, prettier, husky and lint-staged to dev dependency
- Removed wallet disabled type
- Added type for createDomElement function
- Added jest and @types/jest

2022-04-12 06:01 UTC, ajithranka approved these changes

2022-04-12 06:01 UTC, ajithranka commented on .eslintcache
> +[{"/Users/makyl/Documents/repositories/arcana-wallet-embed/tests/index.test.ts":"1","/Users/makyl/Documents/repositories/arcana-wallet-embed/src/config.ts":"2","/Users/makyl/Documents/repositories/ar
This auto-generated file probably needs to be added to `.gitignore`.

2022-04-12 06:04 UTC, makylfang commented on .eslintcache
> +[{"/Users/makyl/Documents/repositories/arcana-wallet-embed/tests/index.test.ts":"1","/Users/makyl/Documents/repositories/arcana-wallet-embed/src/config.ts":"2","/Users/makyl/Documents/repositories/ar
Yeah the last commit is doing that. [3227b5f](https://github.com/arcana-network/wallet/pull/8/commits/3227b5ff2aea8b4e139acdec970f2883625483bf)

Will delete file also it in the next commit so it doesn't shows up in the repo.

2022-04-14 07:01 UTC, makylfang commented
@karthik-durai Can you also check this once? I'll merge it after that.

2022-04-25 05:23 UTC, merged